### ISSUE TITLE
[Feature Request] Generate password

### ISSUE THREAD

**Issue by mmahmad** [blacs30/bitwarden-alfred-workflow#90] opened 2021-07-28 22:00 UTC
Hi,

I'd love to be able to generate a password through this workflow, perhaps with `.bw genpwd` with options to select the complexity of the password.

**Comment by claas-fridtjof-lisowski** [comment] 2021-07-29 08:19
Duplicate of #75 

For passwords I'd recommend this workflow https://github.com/deanishe/alfred-pwgen

**Comment by blacs30** [comment] 2021-07-29 08:20
Duplicate of #75 

For passwords I'd recommend this workflow https://github.com/deanishe/alfred-pwgen

**Closed by blacs30** 2021-07-29 08:20 UTC
